services:
  - type: web
    name: dawai-ki-dukan
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn quickmeds.wsgi:application
    postDeployCommand: python manage.py migrate
    envVars:
      - key: DJANGO_ENV
        value: prod
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: dawai-ki-dukan-j67h.onrender.com,.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://*.onrender.com
      - key: USE_CLOUDINARY
        value: False
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: EMAIL_HOST_USER
        value: tanmaywarthe09@gmail.com
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: RAZORPAY_KEY_ID
        value: rzp_test_tPcdMpc0pKpdgJ
      - key: RAZORPAY_KEY_SECRET
        sync: false
