services:
  - type: web
    name: quickmeds
    runtime: python
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "gunicorn quickmeds.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: false
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: quickmeds-db
          property: connectionString
      - key: USE_MYSQL
        value: true
    autoDeploy: false

databases:
  - name: quickmeds-db
    databaseName: quickmeds_db
    user: quickmeds_user
